/*
  ============================================================
  CONFIG & DATA
  ------------------------------------------------------------
  Edit everything in this file to personalize the website.
  No need to touch HTML/CSS to change the content below.
  ============================================================
*/

// ---- 1. MAIN CONFIG -----------------------------------------------------
const CONFIG = {
    girlfriendName: "Em",
    yourName: "Anh",
    // ISO date string of when you two got together (used by the live counter)
    anniversaryDate: "2025-10-26T00:00:00",
    secretPassword: "ourlittleuniverse",
    songTitle: "Bài hát của chúng ta",
    songArtist: "Bài hát luôn khiến anh nhớ đến em",
    songFile: "assets/music/our-song.mp3",
    videoFile: "assets/video/our-video.mp4",
};

// ---- 2. OUR STORY / TIMELINE -------------------------------------------
const timelineData = [
    {
        date: "04.10.2025",
        title: "Ngày đầu tiên ta gặp nhau.",
        desc: "Anh không biết một cuộc trò chuyện có thể thay đổi mọi thứ.",
        detail:
            "Anh vẫn nhớ chính xác nơi chúng ta đã đứng. Hôm ấy anh không tìm kiếm điều gì, rồi em bất ngờ xuất hiện — và từ đó chẳng điều gì còn bình thường nữa.",
        image: "assets/img/placeholder-01.jpg",
    },
    {
        date: "27.09.2023",
        title: "Buổi hẹn đầu tiên.",
        desc: "Anh đã hồi hộp suốt buổi hẹn. Anh không nghĩ em nhận ra đâu.",
        detail:
            "Anh đã tập trước những điều muốn nói cả trăm lần, rồi quên sạch ngay khi em mỉm cười. Đó là cảm giác hồi hộp tuyệt vời nhất anh từng có.",
        image: "assets/img/placeholder-02.PNG",
    },
    {
        date: "14.02.2025",
        title: "Ngày Valentine đầu tiên của chúng ta.",
        desc: "Mong rằng đây là ngày đầu tiên trong rất nhiều ngày như thế.",
        detail:
            "Không cần gì cầu kỳ, chỉ cần có hai đứa mình — vậy mà vẫn là ngày Valentine tuyệt vời nhất anh từng có, vì em ở đó.",
        image: "assets/img/placeholder-09.PNG",
    },
    {
        date: "26.10.2026",
        title: "Vẫn luôn chọn em.",
        desc: "Mỗi ngày, hết lần này đến lần khác.",
        detail:
            "Có những điều không bao giờ thay đổi. Đây là một trong số đó — anh chọn em hôm nay và mọi ngày sau này.",
        image: "assets/img/placeholder-03.PNG",
    },
];

// ---- 3. OUR MEMORIES / GALLERY -----------------------------------------
// categories: "first" | "dates" | "silly" | "favorite"
const memoriesData = [
    { src: "assets/img/placeholder-05.jpg", category: "first", caption: "Bức ảnh đầu tiên của hai đứa mình." },
    { src: "assets/img/placeholder-01.jpg", category: "first", caption: "Buổi chiều ta chẳng thể ngừng trò chuyện." },
    { src: "assets/img/placeholder-06.MOV", category: "dates", caption: "Buổi hẹn thứ hai, buổi hẹn có cơn mưa." },
    { src: "assets/img/placeholder-02.PNG", category: "dates", caption: "Một buổi hẹn anh không bao giờ muốn quên." },
    { src: "assets/img/placeholder-07.PNG", category: "silly", caption: "Em làm gương mặt này khiến anh cười đến không thở nổi." },
    { src: "assets/img/placeholder-03.PNG", category: "silly", caption: "Cả hai chẳng nhớ vì sao lúc ấy mình lại cười." },
    { src: "assets/img/placeholder-08.PNG", category: "favorite", caption: "Bức ảnh anh thích nhất về em. Luôn luôn là vậy." },
    { src: "assets/images/placeholder-09.svg", category: "favorite", caption: "Ánh mắt của em khi không biết anh đang nhìn." },
    { src: "assets/images/placeholder-10.svg", category: "silly", caption: "Một chút hỗn loạn đáng yêu, mười điểm trên mười." },
    { src: "assets/img/placeholder-04.PNG", category: "favorite", caption: "Bức ảnh này luôn ở trong tâm trí anh." },
];

// ---- 4. OPEN WHEN... LETTERS --------------------------------------------
const openWhenData = [
    {
        title: "Mở khi em nhớ anh",
        message:
            "Chào em yêu. Nếu em đang đọc lá thư này, có lẽ khoảng cách hôm nay khiến nỗi nhớ lớn hơn thường lệ. Nhắm mắt lại một chút nhé — anh vẫn ở bên em trong mỗi bài hát, mỗi khoảnh khắc yên lặng, mỗi lần em ước anh có mặt. Anh cũng nhớ em nhiều như vậy, luôn luôn.",
    },
    {
        title: "Mở khi em buồn",
        message:
            "Anh không biết chuyện gì đã xảy ra, và anh không cần phải biết ngay. Anh chỉ muốn em biết rằng dù là chuyện gì, nó cũng không làm thay đổi tình yêu anh dành cho em. Em có quyền không ổn. Anh sẽ ở đây cho đến khi em ổn hơn.",
    },
    {
        title: "Mở khi em cần một cái ôm",
        message:
            "Hãy coi đây là cái ôm của anh vượt qua mọi khoảng cách đang ngăn chúng ta. Nếu cần, hãy ôm lấy lá thư này nhé. Anh hứa cái ôm thật sẽ đến ngay khi anh có thể trao nó cho em.",
    },
    {
        title: "Mở khi chúng ta cãi nhau",
        message:
            "Anh biết cả hai chúng ta đều bướng bỉnh. Nhưng sau tất cả, anh vẫn là của em và em vẫn là của anh. Hãy cùng hít thở, cùng trò chuyện và nhớ rằng chúng ta đang ở cùng một đội. Anh thà sai cùng em còn hơn đúng mà không có em.",
    },
    {
        title: "Mở khi em muốn biết anh yêu em nhiều thế nào",
        message:
            "Nhiều hơn những vì sao anh vẫn chỉ cho em xem. Nhiều hơn hôm qua, nhưng ít hơn ngày mai. Tình yêu ấy không thể đong đếm, em à — chỉ cần biết đó là điều lớn lao, dịu dàng và chắc chắn nhất anh từng cảm nhận.",
    },
];

// ---- 5. 100 REASONS I LOVE YOU ------------------------------------------
const originalReasonsData = [
    "I love the way you laugh when you're trying not to laugh.",
    "I love how you make ordinary days feel special.",
    "I love the way you say my name when you're half asleep.",
    "I love how you steal the blanket and somehow still get cold.",
    "I love the way you get excited about small things.",
    "I love that you remember the tiny details I mention once.",
    "I love how your voice softens when you're being sincere.",
    "I love the way you dance when you think no one's watching.",
    "I love that you always save me the last bite.",
    "I love how you hum without noticing you're doing it.",
    "I love the way you say 'be careful' every time I leave.",
    "I love how you apologize first, even when you're right.",
    "I love the way your nose scrunches when you laugh too hard.",
    "I love how you text me 'landed safe' every single time.",
    "I love the way you hold my hand in your sleep.",
    "I love how you get shy when I compliment you.",
    "I love the way you fight for the people you love.",
    "I love how you make friends with every stranger.",
    "I love the way you say 'just five more minutes' every morning.",
    "I love how patient you are with me on my worst days.",
    "I love the way you cry at movies and deny it after.",
    "I love how you always know what to say.",
    "I love the way you look at me like I'm the only person in the room.",
    "I love how you send me songs that remind you of us.",
    "I love the way you plan little surprises for no reason.",
    "I love how you never let me walk on the outside of the sidewalk.",
    "I love the way you get competitive over the smallest games.",
    "I love how you remember how I take my coffee.",
    "I love the way you carry my bag without me asking.",
    "I love how you make me laugh until it hurts.",
    "I love the way you say 'I miss you' mid-conversation for no reason.",
    "I love how you always fix my collar before we leave.",
    "I love the way you get nervous meeting new people but do it anyway.",
    "I love how you never go to bed angry.",
    "I love the way you say 'we' instead of 'I'.",
    "I love how you defend me even when I'm not around.",
    "I love the way you look right after waking up.",
    "I love how you make every trip an adventure.",
    "I love the way you listen like every word matters.",
    "I love how you cheer for me louder than anyone.",
    "I love the way you say sorry with your eyes before your words.",
    "I love how you keep every little note I've ever given you.",
    "I love the way you hug like you mean it.",
    "I love how you always know when something's wrong.",
    "I love the way you make our home feel like home.",
    "I love how you get so focused when you're doing something you love.",
    "I love the way you say 'okay, one more episode' and mean five.",
    "I love how you never make me feel silly for caring too much.",
    "I love the way you remember our anniversary down to the hour.",
    "I love how you learned my favorite food without me telling you.",
    "I love the way you say 'come here' when I'm upset.",
    "I love how you make plans just to see me smile.",
    "I love the way you write my name when you're doodling.",
    "I love how you always order dessert 'to share'.",
    "I love the way you look out for my family like they're yours.",
    "I love how you never let a fight last past dinner.",
    "I love the way you say 'we'll figure it out' and mean it.",
    "I love how you laugh at your own jokes before you finish them.",
    "I love the way you kiss my forehead like it's a habit.",
    "I love how you keep believing in me even when I don't.",
    "I love the way you say goodnight like it's the most important word of the day.",
    "I love how you make time for me even on your busiest days.",
    "I love the way you get shy when I take your photo.",
    "I love how you remember every promise you've ever made me.",
    "I love the way you handle my bad days without complaint.",
    "I love how you never tire of my long stories.",
    "I love the way you look at old photos of us and smile.",
    "I love how you say 'I've got you' and I know it's true.",
    "I love the way you make me feel safe in a chaotic world.",
    "I love how you learned to like the things I like, just for me.",
    "I love the way you say my nickname like it's a secret only we know.",
    "I love how you turn bad days into inside jokes.",
    "I love the way you notice when I'm quiet and ask why.",
    "I love how you keep choosing me even on the hard days.",
    "I love the way you plan our future like it's already certain.",
    "I love how you never let me feel alone in a room full of people.",
    "I love the way you say 'proud of you' and actually mean it.",
    "I love how you remember the little anniversaries too.",
    "I love the way you make me laugh at 2am over nothing.",
    "I love how you hold on to hope, even when I lose mine.",
    "I love the way you say 'us' like it's the safest word you know.",
    "I love how you show up, every time, no matter what.",
    "I love the way you make quiet moments feel like enough.",
    "I love how you learned all my little habits without me noticing.",
    "I love the way you say 'come back to me' before I even leave.",
    "I love how you never stop trying to make me smile.",
    "I love the way you love the people I love.",
    "I love how you turned into my favorite person without trying.",
    "I love the way you say 'let's grow old like this'.",
    "I love how gentle you are with things that matter to me.",
    "I love the way you look at me and somehow it still feels like the first time.",
    "I love how you make forever sound like a reasonable idea.",
    "I love the way you say 'I love you' like it never gets old.",
    "I love how our silence is comfortable, not empty.",
    "I love the way you fit into my life like you were always meant to be there.",
    "I love how you make me want to be better, without ever asking me to be.",
    "I love the way you say my name and it sounds like home.",
    "I love how every single day with you still feels like a good idea.",
    "I love the way you are, simply, entirely, and completely you.",
    "I love that out of everyone, I get to choose you — again and again.",
];

const reasonsData = [
    "Anh yêu cách em cười khi cố nhịn cười.",
    "Anh yêu cách em biến những ngày bình thường thành đặc biệt.",
    "Anh yêu cách em gọi tên anh khi còn ngái ngủ.",
    "Anh yêu cách em giành chăn rồi vẫn thấy lạnh.",
    "Anh yêu vẻ hào hứng của em trước những điều nhỏ bé.",
    "Anh yêu việc em nhớ những chi tiết nhỏ anh chỉ nói một lần.",
    "Anh yêu giọng em dịu lại khi em thật lòng.",
    "Anh yêu điệu nhảy của em khi nghĩ rằng chẳng ai đang nhìn.",
    "Anh yêu việc em luôn để dành miếng cuối cho anh.",
    "Anh yêu tiếng em ngân nga mà không nhận ra.",
    "Anh yêu cách em luôn dặn anh phải cẩn thận mỗi khi anh rời đi.",
    "Anh yêu việc em luôn xin lỗi trước, kể cả khi em đúng.",
    "Anh yêu chiếc mũi chun lại của em khi cười quá nhiều.",
    "Anh yêu tin nhắn em luôn gửi: 'Em đã về an toàn'.",
    "Anh yêu cách em nắm tay anh trong lúc ngủ.",
    "Anh yêu vẻ ngại ngùng của em khi được khen.",
    "Anh yêu cách em bảo vệ những người em thương.",
    "Anh yêu việc em có thể kết bạn với bất kỳ ai.",
    "Anh yêu câu 'thêm năm phút nữa thôi' của em mỗi sáng.",
    "Anh yêu sự kiên nhẫn của em trong những ngày tệ nhất của anh.",
    "Anh yêu việc em khóc khi xem phim rồi lại phủ nhận.",
    "Anh yêu việc em luôn biết phải nói gì.",
    "Anh yêu cách em nhìn anh như thể anh là người duy nhất trong phòng.",
    "Anh yêu những bài hát em gửi vì chúng khiến em nhớ đến chúng ta.",
    "Anh yêu những bất ngờ nhỏ em chuẩn bị chẳng vì lý do gì.",
    "Anh yêu việc em luôn đi phía ngoài vỉa hè để bảo vệ anh.",
    "Anh yêu vẻ cạnh tranh của em trong những trò chơi nhỏ nhất.",
    "Anh yêu việc em nhớ anh uống cà phê thế nào.",
    "Anh yêu việc em xách túi giúp anh mà không cần anh nhờ.",
    "Anh yêu cách em khiến anh cười đến đau cả bụng.",
    "Anh yêu lúc em bất chợt nói 'em nhớ anh' giữa cuộc trò chuyện.",
    "Anh yêu việc em luôn chỉnh cổ áo cho anh trước khi ra ngoài.",
    "Anh yêu vẻ hồi hộp của em khi gặp người mới nhưng vẫn cố gắng.",
    "Anh yêu việc em không bao giờ đi ngủ khi đang giận.",
    "Anh yêu cách em nói 'chúng ta' thay vì 'em'.",
    "Anh yêu việc em bênh vực anh ngay cả khi anh không có mặt.",
    "Anh yêu vẻ của em ngay sau khi thức dậy.",
    "Anh yêu cách em biến mỗi chuyến đi thành một cuộc phiêu lưu.",
    "Anh yêu cách em lắng nghe như thể từng lời đều quan trọng.",
    "Anh yêu cách em cổ vũ anh lớn tiếng hơn tất cả mọi người.",
    "Anh yêu ánh mắt em nói lời xin lỗi trước cả khi môi em cất lời.",
    "Anh yêu việc em giữ từng mẩu giấy nhỏ anh từng tặng.",
    "Anh yêu cách em ôm anh bằng tất cả sự chân thành.",
    "Anh yêu việc em luôn nhận ra khi anh có chuyện không ổn.",
    "Anh yêu cách em khiến ngôi nhà của chúng ta thật sự là nhà.",
    "Anh yêu vẻ tập trung của em khi làm điều em yêu thích.",
    "Anh yêu câu 'thêm một tập nữa thôi' nhưng em lại xem thành năm tập.",
    "Anh yêu việc em không bao giờ khiến anh thấy ngốc vì quan tâm quá nhiều.",
    "Anh yêu việc em nhớ ngày kỷ niệm của chúng ta đến từng giờ.",
    "Anh yêu việc em tự tìm hiểu món ăn anh thích mà anh chẳng cần nói.",
    "Anh yêu cách em gọi 'lại đây' khi anh buồn.",
    "Anh yêu những kế hoạch em lập ra chỉ để thấy anh mỉm cười.",
    "Anh yêu cách em viết tên anh khi vẽ nguệch ngoạc.",
    "Anh yêu việc em luôn gọi món tráng miệng với lý do 'để chia nhau'.",
    "Anh yêu cách em quan tâm gia đình anh như gia đình của em.",
    "Anh yêu việc em không để một cuộc cãi vã kéo dài qua bữa tối.",
    "Anh yêu câu 'rồi chúng ta sẽ giải quyết được' của em.",
    "Anh yêu việc em cười vì chính câu đùa của mình trước khi nói xong.",
    "Anh yêu cách em hôn lên trán anh như một thói quen.",
    "Anh yêu việc em vẫn tin vào anh ngay cả khi anh không tin chính mình.",
    "Anh yêu cách em chúc ngủ ngon như thể đó là lời quan trọng nhất ngày.",
    "Anh yêu việc em luôn dành thời gian cho anh dù bận rộn đến đâu.",
    "Anh yêu vẻ ngại ngùng của em khi anh chụp ảnh.",
    "Anh yêu việc em nhớ mọi lời hứa từng dành cho anh.",
    "Anh yêu cách em dịu dàng với những ngày tồi tệ của anh.",
    "Anh yêu việc em không bao giờ chán những câu chuyện dài của anh.",
    "Anh yêu nụ cười của em khi nhìn ảnh cũ của hai đứa.",
    "Anh yêu câu 'có em đây rồi' và biết đó là sự thật.",
    "Anh yêu cách em khiến anh cảm thấy an toàn giữa thế giới hỗn loạn.",
    "Anh yêu việc em học thích những điều anh thích chỉ vì anh.",
    "Anh yêu cách em gọi biệt danh của anh như một bí mật chỉ hai đứa biết.",
    "Anh yêu việc em biến những ngày tệ thành trò đùa riêng của chúng ta.",
    "Anh yêu việc em nhận ra khi anh im lặng và hỏi lý do.",
    "Anh yêu việc em vẫn chọn anh trong cả những ngày khó khăn.",
    "Anh yêu cách em lên kế hoạch cho tương lai như thể điều đó đã chắc chắn.",
    "Anh yêu việc em không bao giờ để anh thấy cô đơn giữa một căn phòng đông người.",
    "Anh yêu câu 'anh tự hào về em' mà em luôn nói thật lòng.",
    "Anh yêu việc em cũng nhớ cả những ngày kỷ niệm nhỏ.",
    "Anh yêu cách em khiến anh cười lúc hai giờ sáng vì chẳng vì điều gì.",
    "Anh yêu việc em vẫn giữ hy vọng ngay cả khi anh đánh mất nó.",
    "Anh yêu cách em nói 'chúng ta' như đó là từ an toàn nhất em biết.",
    "Anh yêu việc em luôn xuất hiện, bất kể chuyện gì xảy ra.",
    "Anh yêu cách em khiến những phút yên lặng cũng trở nên đủ đầy.",
    "Anh yêu việc em học thuộc những thói quen nhỏ của anh mà anh không hề hay biết.",
    "Anh yêu câu 'hãy quay về với em' của em trước cả khi anh rời đi.",
    "Anh yêu việc em không ngừng cố gắng làm anh mỉm cười.",
    "Anh yêu cách em yêu thương những người anh yêu.",
    "Anh yêu việc em trở thành người anh yêu thích nhất mà chẳng cần cố gắng.",
    "Anh yêu câu 'hãy cùng nhau già đi như thế này' của em.",
    "Anh yêu sự dịu dàng của em với những điều quan trọng với anh.",
    "Anh yêu cách em nhìn anh mà vẫn khiến anh có cảm giác như lần đầu gặp gỡ.",
    "Anh yêu việc em khiến mãi mãi nghe như một ý tưởng hoàn toàn hợp lý.",
    "Anh yêu cách em nói 'em yêu anh' như thể câu ấy không bao giờ cũ.",
    "Anh yêu sự im lặng thoải mái giữa chúng ta, không hề trống rỗng.",
    "Anh yêu cách em bước vào cuộc đời anh như thể vốn dĩ em luôn thuộc về nơi này.",
    "Anh yêu việc em khiến anh muốn tốt hơn mà chưa từng yêu cầu anh phải thay đổi.",
    "Anh yêu cách tên anh qua giọng em nghe như quê nhà.",
    "Anh yêu việc mỗi ngày bên em vẫn luôn là một lựa chọn đúng đắn.",
    "Anh yêu em, đơn giản, trọn vẹn và hoàn toàn là chính em.",
    "Anh yêu việc giữa tất cả mọi người, anh được chọn em hết lần này đến lần khác.",
];

// ---- 6. MINI QUIZ ("Em hiểu chúng ta đến đâu?") ------------------------
const quizData = [
    {
        question: "Buổi hẹn đầu tiên của chúng ta ở đâu?",
        options: ["Quán cà phê", "Rạp chiếu phim", "Nhà hàng"],
        correct: 0,
    },
    {
        question: "Chúng ta gặp nhau lần đầu vào ngày nào?",
        options: ["12.08.2023", "27.09.2023", "14.02.2024"],
        correct: 0,
    },
    {
        question: "Bài hát của chúng ta tên là gì?",
        options: ["Một bài hát bất kỳ", "Bài hát của chúng ta", "Bài hát của người khác"],
        correct: 1,
    },
    {
        question: "Anh luôn nói gì trước khi em rời đi?",
        options: ["Về sớm nhé", "Cẩn thận nhé", "Nhắn tin cho anh"],
        correct: 1,
    },
    {
        question: "Bức ảnh nào về em là anh thích nhất?",
        options: ["Một bức ảnh ngốc nghếch", "Bức ảnh em không biết anh đang nhìn", "Một bức ảnh trang trọng"],
        correct: 1,
    },
    {
        question: "Chúng ta thường kết thúc một cuộc cãi vã thế nào?",
        options: ["Không đi ngủ khi còn giận", "Phớt lờ nhau nhiều ngày", "Né tránh chủ đề mãi mãi"],
        correct: 0,
    },
    {
        question: "Anh luôn để dành gì cho em trong bữa tối?",
        options: ["Không gì cả", "Miếng cuối cùng", "Hóa đơn"],
        correct: 1,
    },
    {
        question: "Anh đã học điều gì chỉ vì em?",
        options: ["Món ăn em thích", "Thời khóa biểu của em", "Mật khẩu của em"],
        correct: 0,
    },
    {
        question: "Điều gì xảy ra khi anh chụp ảnh em?",
        options: ["Em tạo dáng tự tin", "Em trở nên ngại ngùng", "Em bỏ chạy"],
        correct: 1,
    },
    {
        question: "Theo anh, kế hoạch của chúng ta là gì?",
        options: ["Sống từng ngày", "Cùng nhau già đi như thế này", "Không nghĩ về nó"],
        correct: 1,
    },
];
